---
spring:
  profiles: development

security:
  basic:
    enabled: false
  user:
    password: jazz

server:
  address: localhost
  port: 9090
logging:
  level:
    org.springframework.web: debug
---

spring:
  profiles:
    active: development
  output:
    ansi:
      enabled: detect
logging:
  file: application.log